# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20161022_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/events', verbose_name='Images'),
        ),
        migrations.AddField(
            model_name='fact',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/facts', verbose_name='Images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/posts', verbose_name='Images'),
        ),
    ]
