# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20161024_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ev_place',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='ev_date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fact',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
