# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20161024_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='', verbose_name='Slug'),
        ),
    ]
