# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='', max_length=20, verbose_name='Icon'),
        ),
    ]
