# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='', max_length=50, verbose_name='Icon'),
        ),
    ]
