# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_remove_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_ua',
            field=models.CharField(default='', max_length=100, verbose_name='Name_ua'),
        ),
    ]
