# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 20:58
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_category_name_ua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='images/posts', verbose_name='Images'),
        ),
    ]
