# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-09-10 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20161125_2258'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='ReadPost',
        ),
        migrations.AlterModelOptions(
            name='readpost',
            options={'ordering': ('-date',), 'verbose_name': 'ReadPost', 'verbose_name_plural': 'ReadPoss'},
        ),
    ]
