# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-09-10 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20190910_1507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readpost',
            options={'ordering': ('-date',), 'verbose_name': 'ReadPost', 'verbose_name_plural': 'ReadPosts'},
        ),
        migrations.AlterField(
            model_name='readpost',
            name='tag',
            field=models.ManyToManyField(related_name='readposts', to='webapp.Tag'),
        ),
    ]
